name: excel_it
description: A library for creating, editing and updating excel sheets.
version: 1.0.0
homepage: https://github.com/kawal7415/excel_it

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  archive: ^2.0.0
  xml: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  path: ^1.5.1
  test: ^1.2.0
  flutter_test:
    sdk: flutter