name: excel_it
description: A library for creating, editing and updating excel sheets.
version: 1.0.0
authors:
- Kawaljeet Singh <kawal74153@gmail.com>
homepage: https://github.com/kawal7415/excel_it

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.0
  xml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.5.1
  test: ^1.2.0

flutter:
  uses-material-design: true