name: excel_it
description: A library for creating, editing and updating excel sheets.
version: 1.0.0
authors:
- Ashumendra Pratap Singh <ashumendrapratap77@gmail.com>
- Kawaljeet Singh <kawal741536@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.0
  xml: ^3.0.0

dev_dependencies:
  path: ^1.5.1
  test: ^1.2.0
  flutter_test:
    sdk: flutter