name: excel_it
description: A lightweight library for parsing and updating spreadsheet documents
version: 1.1.0
authors:
- Ashumendra Pratap Singh <ashumendrapratap77@gmail.com>
- Kawaljeet Singh <kawal7415@gmail.com>

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  xml: ^3.0.0

dev_dependencies:
  path: ^1.5.1
  test: ^1.2.0
